### ISSUE TITLE
A couple of typos in the associated blog post

### ISSUE THREAD

**Issue by robinsonb5** [tomverbeure/intel_jtag_primitive_blog#1]
Thanks for the informative blog and demo code.  I noticed a couple of misleading typos in the blog post which left me confused for a few moments:
The irscan command doesn't take a number-of-bits parameter, so where you say
"You can select the USER0 scan chain like this:
irscan max10.fpga_tap 8 0x00c"
the command should be 
"irscan max10.fpga_tap 0x00c"

and likewise the subsequent instruction for selecting the USER1 chain.

**Comment by tomverbeure** [comment]
Fixed. Thanks!
Tom
